add ci

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -34,8 +34,20 @@ jobs:
         run: |
           docker build -t ${{ github.event.repository.name }}:${VERSION} .
 
-      # Step 4: Tag the image with the registry address and version
+      # Step 4: Check if the Docker image already exists
+      - name: Check if Docker Image Version Exists
+        run: |
+          set -e
+          IMAGE=registry.cn-hangzhou.aliyuncs.com/ledger_github/${{ github.event.repository.name }}:${{ VERSION }}
+          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
+            echo "Error: Docker image $IMAGE already exists. Exiting."
+            exit 1
+          fi
+          echo "Docker image $IMAGE does not exist. Proceeding to push."
+
+      # Step 5: Tag the image with the registry address and version
       - name: Tag Docker Image And Push
+        if: success()
         run: |
           REPO_NAME=${{ github.event.repository.name }}
           docker tag ${REPO_NAME}:${VERSION} registry.cn-hangzhou.aliyuncs.com/ledger_github/${REPO_NAME}:${VERSION}
